local STRINGS = _G.STRINGS
local NAMES = _G.STRINGS.NAMES
local RECIPE_DESC = _G.STRINGS.RECIPE_DESC
local GENERIC = _G.STRINGS.CHARACTERS.GENERIC.DESCRIBE
local WILLOW = _G.STRINGS.CHARACTERS.WILLOW.DESCRIBE
local WOLFGANG = _G.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE
local WENDY = _G.STRINGS.CHARACTERS.WENDY.DESCRIBE
local WX78 = _G.STRINGS.CHARACTERS.WX78.DESCRIBE
local WICKERBOTTOM = _G.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE
local WOODIE = _G.STRINGS.CHARACTERS.WOODIE.DESCRIBE
local MAXWELL = _G.STRINGS.CHARACTERS.WAXWELL.DESCRIBE
local WIGFRID = _G.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE
local WEBBER = _G.STRINGS.CHARACTERS.WEBBER.DESCRIBE
local WINONA = _G.STRINGS.CHARACTERS.WINONA.DESCRIBE
local WARLY = _G.STRINGS.CHARACTERS.WARLY.DESCRIBE
local WORTOX = _G.STRINGS.CHARACTERS.WORTOX.DESCRIBE
local WORMWOOD = _G.STRINGS.CHARACTERS.WORMWOOD.DESCRIBE
local WURT = _G.STRINGS.CHARACTERS.WURT.DESCRIBE
local WALTER = _G.STRINGS.CHARACTERS.WALTER.DESCRIBE
local WANDA = _G.STRINGS.CHARACTERS.WANDA.DESCRIBE

STRINGS.BESTIARY_MONSTER = "Monster"
STRINGS.BESTIARY_ANIMAL = "Animal"
STRINGS.BESTIARY_BOSS = "Boss"
STRINGS.BESTIARY_RAIDBOSS = "Raid Boss"

STRINGS.BESTIARY_AGGRESSIVE = "Aggressive"
STRINGS.BESTIARY_NEUTRAL = "Neutral"
STRINGS.BESTIARY_PASSIVE = "Passive"

STRINGS.NO_BESTIARY_ENTRIES_WARNING = "Looks like you don't have any mob entries."