local STRINGS = GLOBAL.STRINGS

STRINGS.BESTIARY_MONSTER = "Monster"
STRINGS.BESTIARY_ANIMAL = "Animal"
STRINGS.BESTIARY_BOSS = "Boss"
STRINGS.BESTIARY_RAIDBOSS = "Raid Boss"

STRINGS.BESTIARY_AGGRESSIVE = "Aggressive"
STRINGS.BESTIARY_NEUTRAL = "Neutral"
STRINGS.BESTIARY_PASSIVE = "Passive"

STRINGS.NO_BESTIARY_ENTRIES_WARNING = "Looks like you don't have any mob entries."